1. Create a NumPy array of integers from 1 to 10.

In [ ]:
import numpy as np

In [ ]:
arr1=np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Create a 2x3 NumPy array filled with zeros.

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

3. Create a NumPy array of even numbers from 2 to 20

In [ ]:
arr2=np.arange(2,21,2)
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

4. Given two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division between the two arrays.

In [138]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])


In [137]:
arr3=arr1+arr2
print("Sum =",arr3)

Sum = [5 7 9]


In [139]:
arr3=arr2-arr1
print("Difference =",arr3)

Difference = [3 3 3]


In [140]:
arr3=arr1*arr2
print("Product =",arr3)

Product = [ 4 10 18]


In [141]:
arr3=arr2/arr1
print("Division =",arr3)

Division = [4.  2.5 2. ]


5. Compute the mean, median, and standard deviation of a NumPy array
containing 100 random numbers

In [142]:
arr=np.random.randint(0,100,100)
arr

array([69, 70, 57, 99, 58, 41, 75, 58, 92, 32, 90, 73, 38, 63, 50, 74, 69,
       72, 92, 29, 32, 38, 88,  4, 24, 28,  9, 91, 35, 85, 15, 51, 76, 18,
       33, 34, 69, 53, 57,  6,  8, 77, 87, 71, 25, 65, 20, 75, 82,  4,  1,
       97, 20, 36, 19, 62,  0, 14,  9, 22, 75, 92, 91, 46, 60, 50, 13, 32,
       14, 51, 34, 20, 66, 74, 36, 82, 58, 88, 56,  8, 86, 21, 47, 47, 80,
       35, 41, 16,  9, 76, 91, 49, 88, 34,  8, 32,  9, 75, 54, 98])

In [143]:
print("Mean =",arr.mean())

Mean = 49.83


In [144]:
print("Median =",np.median(arr))

Median = 50.5


In [145]:
print("Standard deviation =",np.std(arr))

Standard deviation = 28.561531821665312


6. Reshape a 1D NumPy array of 12 random elements into a 2D array with a
shape of (3, 4).

In [ ]:
arr4=np.random.randint(0,12,12)
arr4.reshape(3,4)

array([[ 0,  5,  8,  2],
       [ 4,  7, 10,  9],
       [ 8,  5,  4,  7]])

7. Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in
the array using NumPy functions.

In [79]:
arr = np.array([1, 2, 3, 4, 5])
print("Square of array =",np.square(arr))

Square of array = [ 1  4  9 16 25]


8. Create a 5x5 identity matrix using NumPy

In [ ]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9. Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and
b = np.array([4, 5, 6])

In [80]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Dot product =",np.dot(a,b))


Dot product = 32


10.Find the index of the maximum value and the index of the minimum value
in a NumPy array.

In [ ]:
arr1=np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
print("Index of the maximum value =",np.argmax(arr1))

Index of the maximum value = 9


In [83]:
print("Index of the minimum value =",np.argmin(arr1))

Index of the minimum value = 0


11.Concatenate two random NumPy arrays horizontally and vertically.

In [ ]:
a=np.random.randint(0,20,12).reshape(4,3)
a


array([[13,  4, 13],
       [13, 18, 16],
       [16,  5, 18],
       [ 0,  8, 17]])

In [ ]:
b=np.random.randint(0,20,12).reshape(4,3)
b

array([[ 4,  0,  3],
       [ 4,  8,  8],
       [19,  7,  8],
       [ 7, 10,  3]])

In [ ]:
np.concatenate((a,b)) #Concatenate  vertically

array([[13,  4, 13],
       [13, 18, 16],
       [16,  5, 18],
       [ 0,  8, 17],
       [ 4,  0,  3],
       [ 4,  8,  8],
       [19,  7,  8],
       [ 7, 10,  3]])

In [ ]:
np.concatenate((a,b),axis=1)  #Concatenate horizontally

array([[13,  4, 13,  4,  0,  3],
       [13, 18, 16,  4,  8,  8],
       [16,  5, 18, 19,  7,  8],
       [ 0,  8, 17,  7, 10,  3]])

12.Given a 2D NumPy array, calculate the sum of each row and each column
separately.

In [57]:
arr5=np.array([[1,2,3,4],[5,6,7,8]])

In [58]:
arr5

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
print("Column wise sum =",np.sum(arr5,axis=0))

Column wise sum = [ 6  8 10 12]


In [64]:
print("Row wise sum =",np.sum(arr5,axis=1))

Row wise sum = [10 26]


13.Find the common elements between two NumPy arrays.

In [65]:
e=np.array([1,2,3,4])


In [66]:
f=np.array([6,5,4,3])

In [69]:
 print("Common elements =",np.intersect1d(e, f))

Common elements = [3 4]


14.Replace all negative values in a NumPy array with zeros.

In [90]:
x=np.array([-3,-2,-1,1,2,3])

In [91]:
x[x<0]=0

In [92]:
x

array([0, 0, 0, 1, 2, 3])

15.Create a NumPy array with random integers between 1 and 100 and then
sort it in ascending order

In [94]:
z=np.random.randint(0,100,8)
z

array([74, 82, 50,  5, 78, 25, 92, 75])

In [97]:
z.sort()
print("Sorted array =",z)

Sorted array = [ 5 25 50 74 75 78 82 92]


16.Calculate the element-wise absolute difference between two NumPy
arrays

In [98]:
p=np.array([[1,2,3,4],[5,6,7,8]])

In [101]:
q=np.array([[6,7,8,9],[9,10,11,12]])

In [103]:
print("Absolute difference =",np.absolute(p-q))

Absolute difference = [[5 5 5 5]
 [4 4 4 4]]


17.Given a 2D NumPy array, extract the first row and the last column.

In [105]:
arr7=np.array([[1,5,3,8],[2,6,7,4],[11,15,13,12]])
arr7

array([[ 1,  5,  3,  8],
       [ 2,  6,  7,  4],
       [11, 15, 13, 12]])

In [108]:
print("First row =",arr7[0:1])

First row = [[1 5 3 8]]


In [112]:
print("Last column =",arr7[:,[3]])

Last column = [[ 8]
 [ 4]
 [12]]


18.Slice a 1D NumPy array to get every other element.

In [116]:
ary=np.array([1,5,3,8,2,6,7,4,11,15,13,12])

In [117]:
ary[0:12:1]

array([ 1,  5,  3,  8,  2,  6,  7,  4, 11, 15, 13, 12])

19.Given a 2D NumPy array, extract a subarray consisting of the central 2x2
elements

In [119]:
g=np.arange(1,13).reshape(3,4)
g

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [124]:
print("Sub array =",g[1:4,1:3])

Sub array = [[ 6  7]
 [10 11]]


20.Reverse a 1D NumPy array using slicing.

In [130]:
ary2=np.array([1,2,3,4,5,6,7,8,9])

In [133]:
print("Reversed array =",ary2[::-1])

Reversed array = [9 8 7 6 5 4 3 2 1]
